version: 2
defaults: &defaults
  docker:
    - image: docker:18.06-git
install_dependency: &install_dependency
  name: Installation of build and deployment dependencies.
  command: |
    apk add --no-cache bash curl
    apk add --no-cache jq py-pip sudo
    sudo pip install awscli --upgrade
    sudo pip install docker-compose
install_deploysuite: &install_deploysuite
  name: Installation of install_deploysuite.
  command: |
    git clone --branch v1.3 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
    cp ./../buildscript/master_deploy.sh .
    cp ./../buildscript/buildenv.sh .
    cp ./../buildscript/awsconfiguration.sh .
restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-lp-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-lp-{{ checksum "package-lock.json" }}
  paths:
    - node_modules

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh
      - save_cache: *save_cache_settings
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh DEV
            source awsenvconf
            ./buildenv.sh -e DEV -b dev-mm-final-score-processor-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,dev-mm-final-score-processor-appvar -i mm-final-score-processor

  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: ./build.sh
      - save_cache: *save_cache_settings
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh PROD
            source awsenvconf
            ./buildenv.sh -e PROD -b prod-mm-final-score-processor-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,prod-mm-final-score-processor-appvar -i mm-final-score-processor

workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context: org-global
          filters:
            branches:
              only:
                - develop
      - "build-prod":
          context: org-global
          filters:
            branches:
              only:
                - master
